/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GatedIndexRouteImport } from './routes/_gated/index'
import { Route as GatedGraphRouteImport } from './routes/_gated/graph'
import { Route as GatedHotspotRouteImport } from './routes/_gated/hotspot'
import { Route as GatedPerangkatRouteImport } from './routes/_gated/perangkat'
import { Route as ApiGraphEther1DotgifRouteImport } from './routes/api/graph/ether1[.]gif'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/_gated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedGraphRoute = GatedGraphRouteImport.update({
  id: '/_gated/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedHotspotRoute = GatedHotspotRouteImport.update({
  id: '/_gated/hotspot',
  path: '/hotspot',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedPerangkatRoute = GatedPerangkatRouteImport.update({
  id: '/_gated/perangkat',
  path: '/perangkat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphEther1DotgifRoute = ApiGraphEther1DotgifRouteImport.update({
  id: '/api/graph/ether1.gif',
  path: '/api/graph/ether1.gif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/graph': typeof GatedGraphRoute
  '/hotspot': typeof GatedHotspotRoute
  '/perangkat': typeof GatedPerangkatRoute
  '/': typeof GatedIndexRoute
  '/api/graph/ether1.gif': typeof ApiGraphEther1DotgifRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/graph': typeof GatedGraphRoute
  '/hotspot': typeof GatedHotspotRoute
  '/perangkat': typeof GatedPerangkatRoute
  '/': typeof GatedIndexRoute
  '/api/graph/ether1.gif': typeof ApiGraphEther1DotgifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/_gated/graph': typeof GatedGraphRoute
  '/_gated/hotspot': typeof GatedHotspotRoute
  '/_gated/perangkat': typeof GatedPerangkatRoute
  '/_gated/': typeof GatedIndexRoute
  '/api/graph/ether1.gif': typeof ApiGraphEther1DotgifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/graph'
    | '/hotspot'
    | '/perangkat'
    | '/'
    | '/api/graph/ether1.gif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/graph'
    | '/hotspot'
    | '/perangkat'
    | '/'
    | '/api/graph/ether1.gif'
  id:
    | '__root__'
    | '/auth'
    | '/_gated/graph'
    | '/_gated/hotspot'
    | '/_gated/perangkat'
    | '/_gated/'
    | '/api/graph/ether1.gif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  GatedGraphRoute: typeof GatedGraphRoute
  GatedHotspotRoute: typeof GatedHotspotRoute
  GatedPerangkatRoute: typeof GatedPerangkatRoute
  GatedIndexRoute: typeof GatedIndexRoute
  ApiGraphEther1DotgifRoute: typeof ApiGraphEther1DotgifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/graph': {
      id: '/_gated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GatedGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/hotspot': {
      id: '/_gated/hotspot'
      path: '/hotspot'
      fullPath: '/hotspot'
      preLoaderRoute: typeof GatedHotspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/perangkat': {
      id: '/_gated/perangkat'
      path: '/perangkat'
      fullPath: '/perangkat'
      preLoaderRoute: typeof GatedPerangkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/ether1.gif': {
      id: '/api/graph/ether1.gif'
      path: '/api/graph/ether1.gif'
      fullPath: '/api/graph/ether1.gif'
      preLoaderRoute: typeof ApiGraphEther1DotgifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  GatedGraphRoute: GatedGraphRoute,
  GatedHotspotRoute: GatedHotspotRoute,
  GatedPerangkatRoute: GatedPerangkatRoute,
  GatedIndexRoute: GatedIndexRoute,
  ApiGraphEther1DotgifRoute: ApiGraphEther1DotgifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
